export type Scheme = Record<string, string>;
export type Lang = "en" | "zh-Hant";
export const translations = {
  en: {
    copyColorValue: "Copy color value", invalidHsl: "Use H: 0–360°, S and L: 0–100%.", invalidRgb: "Use whole numbers from 0 to 255 for R, G and B.", colorPicker: "Color picker", colorFormat: "Color format", invalidHsv: "Use H: 0–360°, S and V: 0–100%.", invalidCmyk: "Use values between 0 and 100% for C, M, Y and K.", studio: "THE COLOR SYSTEM STUDIO", title1: "A little color.", title2: "A whole system.", intro: "Turn a color you love into a harmonious Material 3 palette.", intro2: "Made for your next great interface.", built: "Built on Material Design 3", config: "Make it yours", configSub: "A good palette starts with a little inspiration.", single: "Single color", tri: "Tri-color", source: "Source color", primary: "Primary", secondary: "Secondary", tertiary: "Tertiary", seedHelp: "Your starting point. We’ll find the harmony.", triHelp: "Three starting points. One expressive color system.", shuffle: "Surprise me", presets: "OR START WITH A MOOD", live: "Live preview", previewSub: "Same personality. Two sides.", light: "Light", dark: "Dark", preview: "PREVIEW", cardTitle: "Room for good things.", cardSub: "A fresh start for your next big idea.", explore: "Let’s explore", chip: "Your daily inspiration", saved: "Saved to your collection", save: "Save idea", collection: "Your collection", items: "A little inspiration, all in one place.", palette: "Your color system", paletteSub: "Thoughtfully generated. Ready to build with.", tonal: "Tonal palettes", tokens: "Color tokens", css: "Download CSS", markdown: "Copy Markdown", rich: "Copy rich text", role: "Color role", hex: "HEX", toneHelp: "Click any swatch to copy its hex value.", tokenHelp: "Semantic colors for every part of your interface.", footer: "A little tool for a more colorful internet.", footRight: "Crafted with Material 3 color science", copied: "Copied to clipboard", failed: "Clipboard unavailable. Please try in a secure browser context.", downloaded: "Your CSS is ready", invalid: "Enter a valid 6-digit hex color.", neutral: "Neutral", neutralVariant: "Neutral variant", error: "Error", total: "29 semantic tokens · 6 tonal palettes", note: "Good colors work together.", noteSub: "Every shade has a purpose. Each palette is generated in the HCT color space for perceptual harmony.", mint: "Fresh mint", violet: "Soft violet", blue: "Blue hour", peach: "Peach fuzz", rose: "Rose garden", olive: "Olive grove", mode: "Switch appearance", language: "Language", close: "Close", nav: "Palette generator", tag: "A SMALL SEED. ENDLESS POSSIBILITIES."
  },
  "zh-Hant": {
    copyColorValue: "複製顏色數值", invalidHsl: "H 請輸入 0–360°，S 和 L 請輸入 0–100%。", invalidRgb: "R、G、B 請輸入 0–255 的十進制整數。", colorPicker: "選色器", colorFormat: "色彩格式", invalidHsv: "H 請輸入 0–360°，S 和 V 請輸入 0–100%。", invalidCmyk: "C、M、Y、K 請輸入 0–100%。", studio: "你的色彩系統工作室", title1: "一點色彩，", title2: "完整系統。", intro: "將喜愛的顏色，化成和諧的 Material 3 色盤。", intro2: "為下一個出色的介面而設。", built: "採用 Material Design 3", config: "調出你的色彩", configSub: "好色盤，從一點靈感開始。", single: "單色模式", tri: "三色模式", source: "來源顏色", primary: "主色", secondary: "次色", tertiary: "第三色", seedHelp: "選一個起點，讓我們找到色彩的和諧。", triHelp: "三個色彩起點，一套富有表現力的系統。", shuffle: "給我驚喜", presets: "或從一種心情開始", live: "即時預覽", previewSub: "同一個性，兩種面貌。", light: "淺色", dark: "深色", preview: "元件預覽", cardTitle: "為美好留一點空間。", cardSub: "讓下一個大點子，有個全新的開始。", explore: "開始探索", chip: "每日靈感", saved: "已加入你的收藏", save: "收藏靈感", collection: "你的收藏", items: "把一點一滴的靈感，收藏在一起。", palette: "你的色彩系統", paletteSub: "精心生成，隨時用於創作。", tonal: "色調色盤", tokens: "色彩代碼", css: "下載 CSS", markdown: "複製 Markdown", rich: "複製富文字", role: "色彩角色", hex: "色碼", toneHelp: "點選任何色票，即可複製 HEX 色碼。", tokenHelp: "為介面每一個部分準備的語意色彩。", footer: "讓網絡多一點色彩的小工具。", footRight: "以 Material 3 色彩科學打造", copied: "已複製到剪貼簿", failed: "無法存取剪貼簿，請在安全的瀏覽器環境重試。", downloaded: "CSS 已準備好下載", invalid: "請輸入有效的六位 HEX 色碼。", neutral: "中性色", neutralVariant: "中性色變體", error: "錯誤色", total: "29 個語意色彩 · 6 組色調色盤", note: "好色彩，彼此呼應。", noteSub: "每個色階都有用途。所有色盤均以 HCT 色彩空間生成，呈現視覺上的和諧。", mint: "清新薄荷", violet: "柔和紫羅蘭", blue: "藍調時刻", peach: "柔嫩蜜桃", rose: "玫瑰花園", olive: "橄欖樹林", mode: "切換外觀", language: "語言", close: "關閉", nav: "色盤生成器", tag: "小小色彩種子，無限創作可能。"
  }
};
export const moods = [ { color: "#52796F", key: "mint" }, { color: "#8B74B4", key: "violet" }, { color: "#507DA6", key: "blue" }, { color: "#D58D6E", key: "peach" }, { color: "#AD687C", key: "rose" }, { color: "#7A8052", key: "olive" } ] as const;
export const roleNames: Record<string, string> = { primary: "主色", onPrimary: "主色上的內容", primaryContainer: "主色容器", onPrimaryContainer: "主色容器上的內容", secondary: "次色", onSecondary: "次色上的內容", secondaryContainer: "次色容器", onSecondaryContainer: "次色容器上的內容", tertiary: "第三色", onTertiary: "第三色上的內容", tertiaryContainer: "第三色容器", onTertiaryContainer: "第三色容器上的內容", error: "錯誤色", onError: "錯誤色上的內容", errorContainer: "錯誤色容器", onErrorContainer: "錯誤色容器上的內容", background: "背景", onBackground: "背景上的內容", surface: "表面", onSurface: "表面上的內容", surfaceVariant: "表面變體", onSurfaceVariant: "表面變體上的內容", outline: "外框", outlineVariant: "外框變體", shadow: "陰影", scrim: "遮罩", inverseSurface: "反向表面", inverseOnSurface: "反向表面上的內容", inversePrimary: "反向主色" };
export const humanize = (s: string) => s.replace(/([A-Z])/g, " $1").replace(/^./, c => c.toUpperCase());

export type ColorLabels = typeof translations.en;
